### ISSUE TITLE
Incomplete functionality

### ISSUE THREAD

**Issue by quigley-c** [quigley-c/tdrg#2]
# Incomplete functionality
Currently the tool only takes the first line of the file to generate the random lists. The second and third lines of the input file should indicate other fields to be displayed, for example:
```
#This is the first line, with the bulk of the list
item1,item2,item3,item4,...,itemN

#This line should indicate a special field
#ie: Free units that any player can use
item5,item6

#This one is tricky, should be special paired units
#These units "come together"
#meaning you must have one to get the other
item2:item7, item4:item8
```
The second line here represents a set of "free" units. This should be printed by the tool in a separate field with a header that is read from the input file.

The third line is a special case. Here there are paired units, with `item2:item7` meaning that item2 and item 7 are paired, and the owner of item2 should also inherit item7.

**Comment by Mitchello457** [comment]
I will do my best to work on this part.

My first thought is that we use the coupled characters first because we can fill the remaining spots as needed. We will also need to scale up because some games may have a set of 3 or 4 characters that are tied to the acquisition of the first.

I also noticed that we have a line for banned characters but not for free characters that we append to the end of everyone's character list. I should be able to add this functionality as well. The coupled characters will most likely take a significantly longer amount of time to implement.

**Comment by quigley-c** [comment]
stale
